### ISSUE TITLE
"Password" is still visible when the password gets autocompleted

### ISSUE THREAD

**Issue by yeti1337** [gamekeller/next#63]
![Bug](http://i.imgur.com/IgFZ10n.png)

**Comment by hnrch02** [comment]
- Wie wird autocompleted? Über den Browser oder ein Plugin?
- Welcher Browser?

**Comment by yeti1337** [comment]
Wenn man sein username eingibt, dann füllt er das Passwortfeld mit deinem Passwort.
Browser Firefox 34.0.2
Keine Plugins über Browser

**Comment by yeti1337** [comment]
Good work!
