### ISSUE TITLE
Login, password input isn't sliding down.

### ISSUE THREAD

**Issue by yeti1337** [gamekeller/next#68]
![image](https://cloud.githubusercontent.com/assets/667329/10558365/51ad2680-74cc-11e5-940a-9cc54915ddf8.png)

picture 4 proof.

input just slides down, when clicked at. || password label only slides up, when the input is click at.

**Comment by hnrch02** [comment]
I think this is browser bug. Filed a Chrome bug about it: http://crbug.com/544537
