### ISSUE TITLE
Quickly find online admins

### ISSUE THREAD

**Issue by Bujuhu** [gamekeller/next#71]
PROBLEM:
Some users use the friend system to add Admins to see if and which admins are online.

ZIEL:
It should be possible to quickly find and start chatting with an online admin

LÖSUNG:
![image](https://cloud.githubusercontent.com/assets/2357056/10829706/ea1aebb0-7e7b-11e5-95a8-720b415668ce.png)
 

ERGEBNIS:
Everybody lived happily ever after

**Comment by yeti1337** [comment]
Maybe even pre-login so they can inform us, when they have problem with the webpage, logging in or even registering. 

We could even give every admin some sort of description for further identification like "Specialized in User-Support, Channel-Management and Overall Teamspeak Support" or "Specialized in Social-Media and Website problems"
